# Generated by Django 3.2.7 on 2021-11-18 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211118_1652'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tweet',
        ),
    ]
